
service: dutrinkst # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

  stage: dev
  region: eu-west-1
  profile: default

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  vars: ${file(./serverless.vars.yml)}
  webpack: ./webpack.config.js
  webpackIncludeModules: true
  serverless-offline:
    babelOptions:
      presets: ["es2015", "stage-2"]

functions:
  index:
    handler: lib/server/handlers/indexHandler.dutrinkst
    events:
      - http:
          method: GET
          path: dutrinkst
          integration: lambda
          request: ${file(./serverless.templates.yml):request-html}
          response: ${file(./serverless.templates.yml):response-html}