AWSTemplateFormatVersion: '2010-09-09'
Description: Index Page (S3 and Cloudfront) for dutrinkst
Parameters:
  bucketName:
    Description: Assets bucket name
    Type: String
  originId:
    Description: an origin id for cloudfront
    Type: String
  domainName:
    Description: domain name for cloudfront
    Type: String
  certificateArn:
    Description: certificate arn
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref bucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: AllowPublicAccessToBucketPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*
      Bucket: !Ref S3Bucket

  CloudfrontDistribution:
    Type : AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref domainName
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Sub ${S3Bucket}.s3-website.${AWS::Region}.amazonaws.com
            Id: !Ref originId
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: 'http-only'
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref originId
          ViewerProtocolPolicy: 'redirect-to-https'
        ViewerCertificate:
          AcmCertificateArn: !Ref certificateArn
          SslSupportMethod: sni-only

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Sub https://${S3Bucket.DomainName}
    Description: Name of S3 bucket to hold website content
  DistributionName:
    Value: !GetAtt CloudfrontDistribution.DomainName
    Description: domain name of cloudfront distribution
